### ISSUE TITLE
Pi symbol not well shaped

### ISSUE THREAD

**Issue by flinx42** [jrhunger/2600-digits#10]
The Pi symbol could be improved by getting closer to the actual shape.
- Remove part of the left "foot"
- Dip down the top bar on the left end
See example, where **red** indicates _delete_ and **blue** means _add_
![image](https://user-images.githubusercontent.com/76882443/103468169-60197100-4d4e-11eb-95e3-59483ffd64dd.png)

**Comment by jrhunger** [comment]
How does this look?
![image](https://user-images.githubusercontent.com/7697261/103470218-a31f1880-4d3d-11eb-916f-190c83e8a3d3.png)

**Comment by jrhunger** [comment]
Or this.. i think i messed up the right foot on my first attempt:
![image](https://user-images.githubusercontent.com/7697261/103470236-db265b80-4d3d-11eb-8ae3-fb65af736b98.png)

**Comment by flinx42** [comment]
Getting there, especially with the second attempt.
Might be worth trying putting the legs one closer together, although given the pixel width that may end up too close.

**Comment by jrhunger** [comment]
Closer is too close, i remember from when i was making it at first.  I'm gonna call it good.
