### ISSUE TITLE
Decimal point doesn't align initially

### ISSUE THREAD

**Issue by flinx42** [jrhunger/2600-digits#20]
I've noticed that the decimal point is not aligned with the digits that follow, making larger/smaller gaps to the surrounding digits.
Should be visible on the attached picture.

By the time you've gotten to `3.14` it starts to work though.

![2600-digits-decimal-point-misaligned](https://user-images.githubusercontent.com/76882443/106401665-420e6180-641d-11eb-8939-805e84159ce0.png)

**Comment by jrhunger** [comment]
Interesting! I had not noticed.  This is a problem with my digit files.  Depending on the region of the screen, it is using left nybble, right nybble, left nybble reversed, or right-nybble reversed.  And it seems i have not differentiated the normals from the reversed.
